library(shinytest2)

test_that("{shinytest2} recording: STOPeData", {
  app <- AppDriver$new(name = "STOPeData", height = 1351, width = 2259)
  app$set_window_size(width = 2259, height = 1351)
  app$set_inputs(`campaign-CAMPAIGN_NAME` = "Sam Campaign")
  app$set_inputs(`campaign-CAMPAIGN_START_DATE` = "2025-07-18")
  app$set_inputs(`campaign-CAMPAIGN_END_DATE` = "2025-07-31")
  app$set_inputs(`campaign-RELIABILITY_EVAL_SYS` = "CREED")
  app$set_inputs(`campaign-RELIABILITY_SCORE` = "11")
  app$set_inputs(`campaign-CONFIDENTIALITY_EXPIRY_DATE` = "2025-07-23")
  app$set_inputs(`campaign-ORGANISATION` = "Sam Himself")
  app$set_inputs(`campaign-ENTERED_BY` = "Sam Welch")
  app$expect_values()
})
