library(shinytest2)

test_that("{shinytest2} recording: navButtons", {
  app <- AppDriver$new(name = "navButtons")
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle() # avoid race between input and tab change
  app$expect_values(input = "main-page")
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$expect_values(input = "main-page")
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$expect_values(input = "main-page")
  app$set_inputs(next_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$expect_values(input = "main-page")
  app$set_inputs(previous_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(previous_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(previous_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(previous_section = "click", wait = TRUE)
  app$wait_for_idle()
  app$set_inputs(previous_section = "click", wait = TRUE)
  app$expect_values(input = "main-page")
})
